services:
    asdoria_product_document.listener.admin.menu_builder:
        class: Asdoria\SyliusProductDocumentPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
