imports:
    - "@AsdoriaSyliusProductDocumentPlugin/Resources/config/grids/*.yaml"

doctrine_migrations:
    migrations_paths:
        'Asdoria\SyliusProductDocumentPlugin\Migrations': '@AsdoriaSyliusProductDocumentPlugin/Migrations'

framework:
    serializer:
        mapping:
            paths: ['%kernel.project_dir%/vendor/asdoria/sylius-product-document-plugin/src/Resources/config/serialization']

knp_gaufrette:
    adapters:
        sylius_document:
            local:
                directory: "%kernel.project_dir%/public/media/document"
                create: true
    filesystems:
        sylius_document:
            adapter: sylius_document

flysystem:
    storages:
        sylius.document:
            adapter: 'local'
            options:
                directory: "%kernel.project_dir%/public/media/document"
