asdoria_admin_document_type:
    resource: |
        alias: asdoria.document_type
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show']
        redirect: index
        grid: asdoria_admin_document_type
        permission: true
    type: sylius.resource
